In [1]:
import numpy as np

In [10]:
#arange
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(3.0)

array([0., 1., 2.])

In [4]:
np.arange(4, dtype=float)

array([0., 1., 2., 3.])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(5,20,5)

array([ 5, 10, 15])

In [9]:
np.arange(10,5)

array([], dtype=int32)

In [11]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [13]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.zeros((5, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
#list to array
list_a = [1,2,3,4,5,6,7,8,9]
arr = np.array(list_a)
print(arr)
print(type(list_a))
print(type(arr))

[1 2 3 4 5 6 7 8 9]
<class 'list'>
<class 'numpy.ndarray'>


In [22]:
#ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones((5, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.ones((1, 4), dtype=int)

array([[1, 1, 1, 1]])

In [24]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [25]:
np.ones((4))

array([1., 1., 1., 1.])

In [27]:
np.ones((30, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [29]:
#randint
np.random.randint(10)

4

In [31]:
np.random.randint(5,10)

6

In [39]:
np.random.randint((5, 10))

array([4, 0])

In [40]:
np.random.randint((5, 10, 5))

array([4, 3, 0])

In [42]:
np.random.randint(10,20,(5, 3))

array([[13, 17, 19],
       [13, 10, 17],
       [15, 11, 12],
       [12, 15, 10],
       [13, 15, 18]])

In [44]:
np.random.randint(5, 10, (2, 5))

array([[8, 6, 7, 6, 9],
       [6, 7, 8, 7, 8]])

In [45]:
np.random.randint(2,10,2)

array([2, 9])

In [46]:
np.random.randint(2,9, 10)

array([3, 6, 4, 4, 3, 7, 3, 4, 3, 4])

In [56]:
a = np.array([[0, 1, 2, 3, 4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24],
         [30, 31, 32, 33, 34]])
print(a[0,0]) #0
print(a[-1]) #[30, 31, 33, 34]
print(a[1]) #[10, 11, 12, 13, 14]
print(a[1:3, 1:3]) #[11, 12],[21, 22]
print(a[-1, 1:3]) #[31, 32]

0
[30 31 32 33 34]
[10 11 12 13 14]
[[11 12]
 [21 22]]
[31 32]


In [58]:
x = np.array([1,2,3,1])
y = np.array([1,2,3,4])
a[x,y] #[11, 22, 33, 14]

array([11, 22, 33, 14])

In [63]:
a[a<9]

array([0, 1, 2, 3, 4])

In [68]:
b1 = np.array([False, True, True, False, False])
a[:,b1] # [1,2] [12, 13], [22,23], [32, 33]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]])

In [69]:
a1 = np.array([True, False, False, True])
a[a1, :] #[0,1,2,3,4], [30,31,32, 33, 34]

array([[ 0,  1,  2,  3,  4],
       [30, 31, 32, 33, 34]])