In [4]:
import numpy as np

In [5]:
#arange
np.arange(3)

array([0, 1, 2])

In [6]:
np.arange(3.0)

array([0., 1., 2.])

In [7]:
np.arange(4, dtype=float)

array([0., 1., 2., 3.])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(5,20,5)

array([ 5, 10, 15])

In [11]:
np.arange(10,5)

array([], dtype=int32)

In [12]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [14]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
np.zeros((5, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
#list to array
list_a = [1,2,3,4,5,6,7,8,9]
arr = np.array(list_a)
print(arr)
print(type(list_a))
print(type(arr))

[1 2 3 4 5 6 7 8 9]
<class 'list'>
<class 'numpy.ndarray'>


In [17]:
#ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones((5, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.ones((1, 4), dtype=int)

array([[1, 1, 1, 1]])

In [21]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [22]:
np.ones((4))

array([1., 1., 1., 1.])

In [23]:
np.ones((30, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [24]:
#randint
np.random.randint(10)

9

In [25]:
np.random.randint(5,10)

7

In [26]:
np.random.randint((5, 10))

array([0, 6])

In [27]:
np.random.randint((5, 10, 5))

array([3, 4, 4])

In [28]:
np.random.randint(10,20,(5, 3))

array([[15, 17, 17],
       [15, 19, 19],
       [11, 10, 16],
       [16, 15, 13],
       [18, 10, 18]])

In [29]:
np.random.randint(5, 10, (2, 5))

array([[9, 6, 8, 9, 6],
       [6, 7, 9, 7, 9]])

In [30]:
np.random.randint(2,10,2)

array([3, 9])

In [31]:
np.random.randint(2,9, 10)

array([7, 6, 8, 6, 4, 8, 5, 7, 2, 6])

In [32]:
a = np.array([[0, 1, 2, 3, 4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24],
         [30, 31, 32, 33, 34]])
print(a[0,0]) #0
print(a[-1]) #[30, 31, 33, 34]
print(a[1]) #[10, 11, 12, 13, 14]
print(a[1:3, 1:3]) #[11, 12],[21, 22]
print(a[-1, 1:3]) #[31, 32]

0
[30 31 32 33 34]
[10 11 12 13 14]
[[11 12]
 [21 22]]
[31 32]


In [33]:
x = np.array([1,2,3,1])
y = np.array([1,2,3,4])
a[x,y] #[11, 22, 33, 14]

array([11, 22, 33, 14])

In [34]:
a[a<9]

array([0, 1, 2, 3, 4])

In [35]:
b1 = np.array([False, True, True, False, False])
a[:,b1] # [1,2] [12, 13], [22,23], [32, 33]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]])

In [36]:
a1 = np.array([True, False, False, True])
a[a1, :] #[0,1,2,3,4], [30,31,32, 33, 34]

array([[ 0,  1,  2,  3,  4],
       [30, 31, 32, 33, 34]])

In [37]:
# newaxis
n = np.arange(3) #[0,1,2]
a_naxis = n[:, np.newaxis] #[[0],[1,],[2]
b_naxis = n[np.newaxis, :] #[[0,1,2]]
c_naxis = n[:, np.newaxis, np.newaxis] #[[[0]], [[1]], [[2]]
d_naxis = n[:, np.newaxis]*n #[[0, 0, 0], [0, 1, 2], [0, 2, 4]]
y = np.arange(3,6) #[3, 4, 5]
y_1 = n[:, np.newaxis]*y #[[0, 0, 0], [3, 4, 5], [6, 8, 10]]
print(f"{a_naxis}\n")
print(f"{b_naxis}\n")
print(f"{c_naxis}\n")
print(f"{d_naxis}\n")
print(f"{y_1}\n")
print(f"{n.shape}\n")
print(f"{y_1.shape}\n")

[[0]
 [1]
 [2]]

[[0 1 2]]

[[[0]]

 [[1]]

 [[2]]]

[[0 0 0]
 [0 1 2]
 [0 2 4]]

[[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]]

(3,)

(3, 3)



In [38]:
from numpy import abs

In [39]:
abs(-1)

1

In [40]:
abs(np.array([-1.5, 1.5]))

array([1.5, 1.5])

In [41]:
abs(1.5+1j)

1.8027756377319948

In [42]:
from numpy import absolute

In [44]:
absolute(-1)

1

In [45]:
from numpy import add, multiply
add.accumulate(np.array([1., 2., 3., 4.])) # 1., 1.+2., 1.+2.+3, 1.+2.+3.+4. - [1, 3, 6, 10]

array([ 1.,  3.,  6., 10.])

In [46]:
multiply.accumulate(np.array([1., 2., 3., 4.])) #1*1, 1*2, (1*2)*3, ((1*2)*3)*4 - [1, 2, 6, 24]

array([ 1.,  2.,  6., 24.])

In [52]:
add.accumulate(np.array([[1,2,3], [4,5,6]]), axis=0) #add in column [1,2,3] [5,6,10]

array([[1, 2, 3],
       [5, 7, 9]])

In [54]:
add.accumulate(np.array([[1,2,3], [4,5,6]]), axis=1) #add in row [1, 3, 6] [4, 9, 15]

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [57]:
add(np.array([-1.2, 1.5]), np.array([-1.2, 2.5])) #-0 4.0

array([-2.4,  4. ])

In [58]:
from numpy import all

In [62]:
a = np.array([True, False, True])
print(a.all())
a = np.array([1,2,3])
a.all()>0

False


True

In [65]:
a = np.arange(1,10)
a.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
a.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
mat = np.arange(0, 100).reshape(10, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
mat[0, 2]

2

In [73]:
mat[4, 5]

45

In [74]:
mat[:, 5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [76]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [77]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [78]:
mat[0:10:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [79]:
mat[0:10:3] #0 3 6 9

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
mat[:4] #0-3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [82]:
mat[::-1] #all rows & columns in reverse order

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [83]:
mat[::-2] #-1 -3 -5 -7

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat[2:4, 2:6] #r-(2,3) c-(2, 3, 4,5)

array([[22, 23, 24, 25],
       [32, 33, 34, 35]])

In [86]:
mat[1:2, 2:4] # r-(1) c-(2,3)

array([[12, 13]])

In [87]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [88]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [89]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [90]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [91]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])